# Generated by Django 5.2.13 on 2026-04-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='Принят'),
        ),
    ]
