# Generated by Django 5.2.13 on 2026-04-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_response_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Телефон, Telegram, email и т.д.', max_length=200, verbose_name='Контакты для связи'),
        ),
    ]
