# Generated by Django 5.2.13 on 2026-04-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ad_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='reply',
            field=models.TextField(blank=True, verbose_name='Ответ автора'),
        ),
    ]
