# Generated by Django 5.2.13 on 2026-04-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_response_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Телефон, Telegram, email', max_length=200, verbose_name='Контакты для связи'),
        ),
    ]
